SELECT N.N_NAME AS NAT_NAME, sum(L.L_QUANTITY * (L.L_EXTENDEDPRICE - L.L_DISCOUNT)) AS order_volume
FROM CUSTOMER AS C, LINEITEM AS L, ORDERS AS O, SUPPLIER AS S, NATION AS N
WHERE   O.O_CUSTKEY = C.C_CUSTKEY
        AND O.O_ORDERKEY = L.L_ORDERKEY
        AND L.L_SUPPKEY = S.S_SUPPKEY
        AND C.C_NATIONKEY = S.S_NATIONKEY
        AND C.C_NATIONKEY = N.N_NATIONKEY
GROUP BY NAT_NAME
ORDER BY NAT_NAME