SELECT  S.S_NAME, count(DISTINCT O.O_CUSTKEY)
FROM LINEITEM L, ORDERS O, SUPPLIER S
WHERE L.L_ORDERKEY = O.O_ORDERKEY
AND S.S_SUPPKEY = L.L_SUPPKEY
GROUP BY L.L_SUPPKEY
HAVING count(DISTINCT O.O_CUSTKEY) > 615
ORDER BY count(DISTINCT O.O_CUSTKEY) DESC